image: maven:3.6.3-openjdk-11

pipelines:
  default:
    - step:
        name: Build
        caches:
          - maven
        script:
          - mvn clean install

    - step:
        name: Test
        caches:
          - maven
        script:
          - mvn test
